# Импорты и настройки

In [ ]:
# coding: utf-8
# наше всё
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
import plotly.graph_objects as go

#настройки pandas, с которыми лучше почти всегда
pd.set_option('display.max_rows', 45000)
pd.set_option('display.max_columns', 50000)
pd.set_option('display.max_colwidth', 5000)

# Получение данных и проверки

In [13]:
sorce_df = pd.read_csv('visual_challenge_ver_0.csv')
sorce_df['calendar_date'] = pd.to_datetime(sorce_df['calendar_date'])

In [14]:
sorce_df.sample(3)

,art_id,calendar_date,user_visits,sids_visits,events_visits,sales_qty,revenue,avg_sales_catalogue_price,avg_dim_price
28,86945401,2026-02-14,3,3,3,0.0,0.0,0.0,0.0
10,243463,2026-02-22,56,80,222,6.0,336.0,60.0,59.9
13,86630365,2026-02-12,166,196,278,6.0,3604.0,679.0,749.0

In [15]:
sorce_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   art_id                     52 non-null     int64
 1   calendar_date              52 non-null     datetime64[ns]
 2   user_visits                52 non-null     int64
 3   sids_visits                52 non-null     int64
 4   events_visits              52 non-null     int64
 5   sales_qty                  52 non-null     float64
 6   revenue                    52 non-null     float64
 7   avg_sales_catalogue_price  52 non-null     float64
 8   avg_dim_price              52 non-null     float64
dtypes: datetime64[ns](1), float64(4), int64(4)
memory usage: 3.8 KB

In [16]:
sorce_df.describe()

,art_id,calendar_date,user_visits,sids_visits,events_visits,sales_qty,revenue,avg_sales_catalogue_price,avg_dim_price
count,5.200000e+01,52,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000
mean,7.905905e+07,2026-02-18 00:00:00,68.211538,83.519231,155.423077,3.346154,1007.423077,451.192308,474.801923
min,2.434630e+05,2026-02-12 00:00:00,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,6.503364e+07,2026-02-15 00:00:00,17.500000,17.750000,24.750000,1.000000,254.500000,60.000000,59.900000
50%,8.678788e+07,2026-02-18 00:00:00,47.500000,55.000000,75.000000,2.500000,446.000000,260.000000,289.000000
75%,1.008133e+08,2026-02-21 00:00:00,88.500000,121.750000,263.000000,6.000000,1504.750000,679.000000,749.000000
max,1.424170e+08,2026-02-24 00:00:00,243.000000,277.000000,778.000000,11.000000,4034.000000,2199.000000,2199.000000
std,5.135294e+07,NaN,69.891046,84.940692,195.931395,2.949806,1195.902159,632.084384,637.299389

In [19]:
sorce_df['art_id'].value_counts()

art_id
243463       13
86630365     13
86945401     13
142416959    13
Name: count, dtype: int64

# Задача 1
Построить подневную динамику выручки одной книжки

# Задача 2
Показать взаимное влияние числа покупок и среднего чека в динамике

# Задача 3
Максимально компактно показать 3 параметра книжки на одном таймлайне: трафик, цену и выручку.